// Custom shader file for ffa_me.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

ffa_me/B612ECB0139FD472941E00961336CE39
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.19531
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/DFEB2684F171DD42D62022E5B9F19373
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/CA819BD05C617C9831C5BA5F8E840216
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.16406 0.00000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/D9B3283D593921FE6D159BFDCD4774BF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.21094
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/0F9B0A0223D71FCB4BDE643CBF114FF4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/3E5F280EB95534096CC09808A0ADB2E1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.68750 0.20312
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/EB633EDCB9BC5E34CB0CE1A6041D7BE4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/7279B506B9A9EB071BC153B4578456E6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/1CBCDF6C99C23A26D0711C6CCA12DEA6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.58594 0.16406
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/BC7299612310EE8CD42B186E82484589
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/5CCE73D05A13464211EB952CDBF7ACBC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/2E8E1A5BEAFBCB16A46D8399A8955904
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.00000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/D4E9ABFF85025659ECBE463A057F1238
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.45312 0.50781
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/8366B97692C931572B7A898DE6910190
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00781 -0.57812
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/C4B3EAF838E3AA6AE1A7F05E6948079B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.28906 -0.42188
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/42169147D7C7B74D8B1E8E52952D2A3F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.68750 -0.42188
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/F707B48D8AE70A4254C149B7F3BEA2C6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.10156
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/0580969D2ED7A717B15456DF52A878A3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/00888EDB18C77BB843C7A50C2D5F53ED
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/B9A4D129F8528D9D68448F6F81306F6A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/canyon.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/A18F698098A44510A4266DD551323578
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.65625 -0.19531
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/97618B8888480EA17767AA9607A77DE0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/915A14CFDB348360CAA929A022652CC7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 -0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/CA32B3ECEBEAA6A092DF8F9441C62C95
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/3797C3C64D4FA9487346F2EF2034439D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/1AFDEDA9A3072D6056385F33B7708396
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/6AB0E557F5F4DD0D2A92D4CB83BC6D65
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.16406
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/F85668ED96BEC0DC7AC77898F694275E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/0BDBB6C30AEC98BD78478545128ADC14
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.10156
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/AFB4D6997DF0E09AE1840EE85C72E7AC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 -0.50000
	}

	{
		map textures/rdm/cardboard.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/5565170293DA4A9869B0BE61EF365CCE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/B23BB8D49399868E71EF0595A162A3B6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/concrete.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ffa_me/2CA37A838ED943042831E0B5FAD5EE3A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ffa_me/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave noise 0.5 1 0 5.37 // style 3
		tcGen lightmap
	}

	{
		map textures/rdm/canyon.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}


// Shaders to force nomipmaps flag on external lightmap images:

maps/ffa_me/nomipmaps0
{
	nomipmaps
	{
		animmap .0042 maps/ffa_me/lm_0000.tga maps/ffa_me/lm_0001.tga maps/ffa_me/lm_0002.tga maps/ffa_me/lm_0003.tga maps/ffa_me/lm_0004.tga maps/ffa_me/lm_0005.tga
	}
}

